name: Mongo Build

on:
  push:
    branches: main
    paths: 
    - 'mongo/**'

jobs:
  main:
    runs-on: Ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: hadoopaccount
          password: dckr_pat_umcCGy1S6ZhL6sXrys0eKtRXP-U
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: mongo/.
          file: mongo/Dockerfile
          push: true
          tags: aquilin/mean-mongo:latest
          secrets: |
            GIT_AUTH_TOKEN=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
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
