name: Nginx Build

on:
  push:
    branches: master
    paths: 
    - 'loadbalancer/**'

jobs:
  main:
    runs-on: Ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: aquilin
          password: dckr_pat_1AefH6gZOQsTVKXwEX-q_s-mF6o
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: loadbalancer/.
          file: loadbalancer/Dockerfile
          push: true
          tags: aquilin/mean-nginx:latest
          secrets: |
            GIT_AUTH_TOKEN=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
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
